#%RAML 1.0 Library
usage: Common Lib is used to share common fragments across different projects

types:
  amount: !include types/amount.raml
  transactionResponse: !include types/transaction-response.raml
  uuid: !include types/uuid.raml
  error: !include types/error.raml